spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      schema: KeyBank

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  account-service:
    url: http://localhost:8081  # Points to Account Service for validation

